apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-deployment
  labels:
    app: hackathon-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-deployment
  template:
    metadata:
      labels:
        app: hackathon-deployment
    spec:
      containers:
        - name: app
          image: deiro1/app-hackathon:latest
          command: ["sh", "-c", "npm run generate && npm run migrate && npm run start"]
          ports:
            - containerPort: 6001
          resources:
            requests:
              cpu: 333m
            limits:
              cpu: 999m
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: NODE_ENV
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: POSTGRES_DB
            - name: POSTGRES_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: POSTGRES_DB_HOST                  
            - name: POSTGRES_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: POSTGRES_DB_PORT
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: POSTGRES_DB_USER
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: POSTGRES_DB_PASSWORD                  
            - name: SQS_REGION
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: SQS_REGION                  
            - name: SQS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: SQS_ACCESS_KEY_ID                  
            - name: SQS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: SQS_SECRET_ACCESS_KEY                  
            - name: QUEUE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: secret-hackathon
                  key: QUEUE_EMAIL                  